package com.openecosystem.os.common.security;

public enum AuthorizationDecisionCode {
  ALLOW_OWNER,
  ALLOW_WORKSPACE_VISIBILITY,
  ALLOW_USER_GRANT,
  DENY_UNAUTHENTICATED,
  DENY_WORKSPACE_MISMATCH,
  DENY_RESOURCE_NOT_FOUND,
  DENY_INACTIVE_MEMBERSHIP,
  DENY_NO_POLICY,
  DENY_UNSUPPORTED
}
