apiVersion: v1
kind: Namespace
metadata:
  name: open-ecosystem-os
  labels:
    app.kubernetes.io/name: open-ecosystem-os
    app.kubernetes.io/part-of: open-ecosystem-os
---
apiVersion: v1
kind: Namespace
metadata:
  name: open-ecosystem-data
  labels:
    app.kubernetes.io/name: open-ecosystem-data
    app.kubernetes.io/part-of: open-ecosystem-os
---
apiVersion: v1
kind: Namespace
metadata:
  name: open-ecosystem-observability
  labels:
    app.kubernetes.io/name: open-ecosystem-observability
    app.kubernetes.io/part-of: open-ecosystem-os
