apiVersion: v1
kind: Namespace
metadata:
  name: open-ecosystem-os
---
apiVersion: v1
kind: Namespace
metadata:
  name: open-ecosystem-data
---
apiVersion: v1
kind: Namespace
metadata:
  name: open-ecosystem-observability
