apiVersion: v1
kind: ConfigMap
metadata:
  name: open-ecosystem-config
  namespace: open-ecosystem-os
data:
  APP_ENV: "kubernetes-dev"
  APP_BASE_URL: "http://open-ecosystem.local"
  NEXT_PUBLIC_API_BASE_URL: ""
  API_BASE_URL: "http://open-ecosystem-api.open-ecosystem-os.svc.cluster.local:8080"
  S3_ENDPOINT: "http://minio.open-ecosystem-data.svc.cluster.local:9000"
  RABBITMQ_HOST: "rabbitmq.open-ecosystem-data.svc.cluster.local"
  MEILISEARCH_HOST: "http://meilisearch.open-ecosystem-data.svc.cluster.local:7700"
