apiVersion: v1
kind: ConfigMap
metadata:
  name: open-ecosystem-config
  namespace: open-ecosystem-os
data:
  APP_ENV: "development"
  NEXT_PUBLIC_API_BASE_URL: "/api"
  MEILISEARCH_INDEX_NAME: "openecosystem_documents"
