apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-ecosystem-web
  namespace: open-ecosystem-os
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: web
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-ecosystem-api
  namespace: open-ecosystem-os
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: api
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-ecosystem-worker
  namespace: open-ecosystem-os
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: worker
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
