import type {
  OcrJobDetail,
  OcrLifecycleEntry,
  OcrLifecyclePhase,
} from "@/lib/media-api";

export type MediaState =
  | "normal"
  | "loading"
  | "empty"
  | "error"
  | "permission-denied";

function eventEntry(
  entryId: string,
  label: string,
  phase: OcrLifecyclePhase,
  eventType: string,
  occurredAt: string,
  source: string,
  correlationId: string,
  causationId: string | null,
  status: string,
  consumers: string[] = [],
): OcrLifecycleEntry {
  return {
    entryId,
    phase,
    kind: "event",
    label,
    status,
    observed: true,
    occurredAt,
    source,
    event: {
      eventId: entryId,
      eventType,
      eventVersion: 1,
      correlationId,
      causationId,
      publicationState: "publish_recorded",
      publishedAt: occurredAt,
      consumptions: consumers.map((consumer) => ({
        consumer,
        state: "consumption_recorded",
        consumedAt: occurredAt,
      })),
    },
    workflow: null,
    retry: null,
    failure: null,
    resource: null,
  };
}

function workflowEntry(
  entryId: string,
  label: string,
  occurredAt: string,
  status: string,
  stepKey: string | null,
  actionType: string | null,
): OcrLifecycleEntry {
  return {
    entryId,
    phase: "workflow",
    kind: stepKey ? "workflow_step" : "workflow_execution",
    label,
    status,
    observed: true,
    occurredAt,
    source: "flows",
    event: null,
    workflow: {
      executionId: "wfe_invoice_demo",
      workflowId: "flow_invoice_automation",
      workflowVersionId: "wfv_invoice_automation_v2",
      workflowVersionNumber: 2,
      stepKey,
      actionType,
      retryCount: 0,
    },
    retry: null,
    failure: null,
    resource: {
      resourceType: stepKey ? "workflow_step" : "workflow_execution",
      resourceId: entryId,
    },
  };
}

function pendingEntry(
  entryId: string,
  label: string,
  phase: "ocr" | "workflow",
  attemptCount: number,
  maxAttempts: number,
  nextAttemptAt: string | null,
): OcrLifecycleEntry {
  return {
    entryId,
    phase,
    kind: "pending",
    label,
    status: "awaiting",
    observed: false,
    occurredAt: null,
    source: phase === "ocr" ? "media" : "flows",
    event: null,
    workflow: null,
    retry: { attemptCount, maxAttempts, nextAttemptAt },
    failure: null,
    resource: null,
  };
}

export const mediaMockJobs: OcrJobDetail[] = [
  {
    jobId: "ocr_invoice_demo",
    fileId: "file_invoice_demo",
    fileName: "Invoice_2026_05.pdf",
    contentType: "application/pdf",
    status: "completed",
    provider: "mock",
    attemptCount: 1,
    maxAttempts: 3,
    extractedText:
      "Mock OCR result\nInvoice number: TEST-INV-2026-0001\nSupplier: Demo Supplies S.L. (fake/test data)\nTest NIF: B00000000 (test data)\nTest IBAN: ES00 0000 0000 0000 0000 0000 (test data)\nTotal: 124.00 EUR\nDue date: 2026-06-15",
    extractedTextLength: 232,
    failureCode: null,
    failureMessage: null,
    correlationId: "corr_invoice_demo",
    queuedAt: "2026-05-22T09:15:10Z",
    processingStartedAt: "2026-05-22T09:15:22Z",
    completedAt: "2026-05-22T09:15:34Z",
    failedAt: null,
    updatedAt: "2026-05-22T09:15:34Z",
    nextAttemptAt: null,
    lifecycle: {
      state: "complete",
      outcome: "completed",
      entries: [
        eventEntry(
          "evt_invoice_uploaded",
          "File uploaded",
          "upload",
          "FileUploaded",
          "2026-05-22T09:15:00Z",
          "drive",
          "corr_invoice_demo",
          null,
          "completed",
          ["media.file-uploaded.ocr-job"],
        ),
        eventEntry(
          "evt_invoice_requested",
          "OCR queued",
          "ocr",
          "OcrRequested",
          "2026-05-22T09:15:10Z",
          "media",
          "corr_invoice_demo",
          "evt_invoice_uploaded",
          "queued",
          ["worker.ocr-requested.processor"],
        ),
        eventEntry(
          "evt_invoice_started",
          "OCR processing started",
          "ocr",
          "OcrStarted",
          "2026-05-22T09:15:22Z",
          "media",
          "corr_invoice_demo",
          "evt_invoice_requested",
          "processing",
        ),
        eventEntry(
          "evt_invoice_completed",
          "OCR completed",
          "ocr",
          "OcrCompleted",
          "2026-05-22T09:15:34Z",
          "media",
          "corr_invoice_demo",
          "evt_invoice_requested",
          "completed",
          ["flows.ocr-completed.workflow-trigger"],
        ),
        workflowEntry(
          "wfe_invoice_demo",
          "Workflow execution started",
          "2026-05-22T09:15:35Z",
          "running",
          null,
          null,
        ),
        workflowEntry(
          "wfs_extract_invoice_demo",
          "Extract invoice fields",
          "2026-05-22T09:15:36Z",
          "completed",
          "extract-invoice-fields",
          "extract_invoice_fields",
        ),
        eventEntry(
          "evt_invoice_notification",
          "Notification created",
          "notification",
          "NotificationCreated",
          "2026-05-22T09:15:37Z",
          "notifications",
          "corr_invoice_demo",
          "evt_invoice_completed",
          "completed",
        ),
        eventEntry(
          "evt_invoice_indexing_requested",
          "Search indexing requested",
          "search",
          "IndexingRequested",
          "2026-05-22T09:15:38Z",
          "search",
          "corr_invoice_demo",
          "evt_invoice_completed",
          "queued",
          ["worker.search-indexing.processor"],
        ),
        eventEntry(
          "evt_invoice_indexing_completed",
          "Search indexing completed",
          "search",
          "IndexingCompleted",
          "2026-05-22T09:15:39Z",
          "search",
          "corr_invoice_demo",
          "evt_invoice_indexing_requested",
          "completed",
        ),
        {
          entryId: "aud_invoice_demo",
          phase: "audit",
          kind: "audit",
          label: "flows.invoice_automation.completed",
          status: "success",
          observed: true,
          occurredAt: "2026-05-22T09:15:40Z",
          source: "audit",
          event: null,
          workflow: null,
          retry: null,
          failure: null,
          resource: {
            resourceType: "workflow_execution",
            resourceId: "wfe_invoice_demo",
          },
        },
      ],
    },
  },
  {
    jobId: "ocr_receipt_processing",
    fileId: "file_receipt_demo",
    fileName: "Receipt_scan.png",
    contentType: "image/png",
    status: "processing",
    provider: "mock",
    attemptCount: 1,
    maxAttempts: 3,
    extractedText: null,
    extractedTextLength: null,
    failureCode: null,
    failureMessage: null,
    correlationId: "corr_receipt_demo",
    queuedAt: "2026-05-22T10:03:12Z",
    processingStartedAt: "2026-05-22T10:03:18Z",
    completedAt: null,
    failedAt: null,
    updatedAt: "2026-05-22T10:03:18Z",
    nextAttemptAt: null,
    lifecycle: {
      state: "active",
      outcome: "in_progress",
      entries: [
        eventEntry(
          "evt_receipt_uploaded",
          "File uploaded",
          "upload",
          "FileUploaded",
          "2026-05-22T10:03:00Z",
          "drive",
          "corr_receipt_demo",
          null,
          "completed",
          ["media.file-uploaded.ocr-job"],
        ),
        eventEntry(
          "evt_receipt_requested",
          "OCR queued",
          "ocr",
          "OcrRequested",
          "2026-05-22T10:03:12Z",
          "media",
          "corr_receipt_demo",
          "evt_receipt_uploaded",
          "queued",
        ),
        eventEntry(
          "evt_receipt_started",
          "OCR processing started",
          "ocr",
          "OcrStarted",
          "2026-05-22T10:03:18Z",
          "media",
          "corr_receipt_demo",
          "evt_receipt_requested",
          "processing",
        ),
        pendingEntry(
          "ocr_receipt_processing:awaiting-outcome",
          "Awaiting OCR outcome",
          "ocr",
          1,
          3,
          null,
        ),
      ],
    },
  },
  {
    jobId: "ocr_contract_queued",
    fileId: "file_contract_demo",
    fileName: "Signed_contract.pdf",
    contentType: "application/pdf",
    status: "queued",
    provider: "mock",
    attemptCount: 1,
    maxAttempts: 3,
    extractedText: null,
    extractedTextLength: null,
    failureCode: "MOCK_OCR_FAILED",
    failureMessage:
      "OCR processing did not complete. Use the correlation ID for permitted diagnostics.",
    correlationId: "corr_contract_demo",
    queuedAt: "2026-05-22T10:08:00Z",
    processingStartedAt: "2026-05-22T10:08:10Z",
    completedAt: null,
    failedAt: null,
    updatedAt: "2026-05-22T10:09:00Z",
    nextAttemptAt: "2026-05-22T10:12:00Z",
    lifecycle: {
      state: "active",
      outcome: "in_progress",
      entries: [
        eventEntry(
          "evt_contract_uploaded",
          "File uploaded",
          "upload",
          "FileUploaded",
          "2026-05-22T10:07:50Z",
          "drive",
          "corr_contract_demo",
          null,
          "completed",
          ["media.file-uploaded.ocr-job"],
        ),
        eventEntry(
          "evt_contract_requested",
          "OCR queued",
          "ocr",
          "OcrRequested",
          "2026-05-22T10:08:00Z",
          "media",
          "corr_contract_demo",
          "evt_contract_uploaded",
          "queued",
        ),
        eventEntry(
          "evt_contract_started",
          "OCR processing started",
          "ocr",
          "OcrStarted",
          "2026-05-22T10:08:10Z",
          "media",
          "corr_contract_demo",
          "evt_contract_requested",
          "processing",
        ),
        {
          entryId: "ocr_contract_queued:retry-scheduled",
          phase: "ocr",
          kind: "job",
          label: "OCR retry scheduled",
          status: "retrying",
          observed: true,
          occurredAt: "2026-05-22T10:09:00Z",
          source: "media",
          event: null,
          workflow: null,
          retry: null,
          failure: {
            code: "MOCK_OCR_FAILED",
            reason:
              "OCR processing did not complete. Use the correlation ID for permitted diagnostics.",
          },
          resource: {
            resourceType: "ocr_job",
            resourceId: "ocr_contract_queued",
          },
        },
        pendingEntry(
          "ocr_contract_queued:awaiting-ocr",
          "Awaiting scheduled OCR retry",
          "ocr",
          1,
          3,
          "2026-05-22T10:12:00Z",
        ),
      ],
    },
  },
  {
    jobId: "ocr_scan_failed",
    fileId: "file_scan_failed",
    fileName: "Damaged_scan.jpeg",
    contentType: "image/jpeg",
    status: "failed",
    provider: "mock",
    attemptCount: 3,
    maxAttempts: 3,
    extractedText: null,
    extractedTextLength: null,
    failureCode: "MOCK_OCR_FAILED",
    failureMessage: "Mock OCR provider failed",
    correlationId: "corr_failed_demo",
    queuedAt: "2026-05-21T16:20:00Z",
    processingStartedAt: "2026-05-21T16:23:00Z",
    completedAt: null,
    failedAt: "2026-05-21T16:23:02Z",
    updatedAt: "2026-05-21T16:23:02Z",
    nextAttemptAt: null,
    lifecycle: {
      state: "complete",
      outcome: "failed",
      entries: [
        eventEntry(
          "evt_failed_uploaded",
          "File uploaded",
          "upload",
          "FileUploaded",
          "2026-05-21T16:20:00Z",
          "drive",
          "corr_failed_demo",
          null,
          "completed",
          ["media.file-uploaded.ocr-job"],
        ),
        eventEntry(
          "evt_failed_requested",
          "OCR queued",
          "ocr",
          "OcrRequested",
          "2026-05-21T16:20:10Z",
          "media",
          "corr_failed_demo",
          "evt_failed_uploaded",
          "queued",
          ["worker.ocr-requested.processor"],
        ),
        eventEntry(
          "evt_failed_started",
          "OCR processing started",
          "ocr",
          "OcrStarted",
          "2026-05-21T16:23:00Z",
          "media",
          "corr_failed_demo",
          "evt_failed_requested",
          "processing",
        ),
        {
          ...eventEntry(
            "evt_failed_terminal",
            "OCR failed",
            "ocr",
            "OcrFailed",
            "2026-05-21T16:23:02Z",
            "media",
            "corr_failed_demo",
            "evt_failed_requested",
            "failed",
          ),
          failure: {
            code: "MOCK_OCR_FAILED",
            reason:
              "OCR processing did not complete. Use the correlation ID for permitted diagnostics.",
          },
        },
      ],
    },
  },
];

export function parseMediaState(
  value: string | string[] | undefined,
): MediaState | undefined {
  const state = Array.isArray(value) ? value[0] : value;
  return state === "normal" ||
    state === "loading" ||
    state === "empty" ||
    state === "error" ||
    state === "permission-denied"
    ? state
    : undefined;
}
